Mission09_sideaton/Components/CartSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Mission09_sideaton.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Mission09_sideaton.Components
{
    public class CartSummaryViewComponent : ViewComponent
    {
        private ShoppingCart cart;
        public CartSummaryViewComponent(ShoppingCart cartService)
        {
            cart = cartService;
        }
        public IViewComponentResult Invoke()
        {
            return View(cart);
        }
    }
}

Mission09_sideaton/Components/CategoriesViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Mission09_sideaton.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Mission09_sideaton.Components
{
    public class CategoriesViewComponent : ViewComponent
    {
        private IBookstoreRepository repo { get; set; }
        public CategoriesViewComponent (IBookstoreRepository temp)
        {
            repo = temp;
        }
        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedCategory = RouteData?.Values["bookCategory"];
            var cats = repo.Books
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x);
            return View(cats);
        }
    }
}

Mission09_sideaton/Views/Shared/BookSummary.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model Book
@* cards to disaply info about each book *@
<div class="card card-outline-primary m-1 p-1">
    <div class="bg-light p-1">
        <h4 class="text-center">@Model.Title</h4>
        <span class="badge bg-success" style="float:right">
            Category: @Model.Category
        </span>
    </div>

    <ul>
        <li>Author: @Model.Author</li>
        <li>Publisher: @Model.Publisher</li>
        <li>ISBN: @Model.Isbn</li>
        <li>Classification: @Model.Classification</li>
        <li>Page Count: @Model.PageCount</li>
        <li>Price: $@Model.Price</li>
    </ul>
    @* add to cart button. it also saves the location so the user can return later *@
    <form method="post" asp-page="/Cart">
        <input type="hidden" asp-for="@Model.BookId"/>
        <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />
        <span class="card-text">
            <button type="submit" class="btn btn-success btn-sm float-end">Add to Cart</button>
        </span>
    </form>
</div>

Mission09_sideaton/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="/lib/css/bootstrap.min.css" rel="stylesheet" />
    <link href="/lib/font-awesome/css/all.min.css" rel="stylesheet" />
</head>
<body>
    <div class="bg-dark text-white p-2">
        <div class="container-fluid">
            <div class="row">
                <div class="col-6 text-end w-100">
                    <vc:cart-summary />
                </div>
            </div>
        </div>
    </div>
    <div class="bg-dark text-white p-2 text-center">
        <span class="navbar-brand m-lg-2 text-uppercase">online bookstore</span>
    </div>
    @* Creates two columns, one for filtering, and the other to display books *@
    <div class="row m-1 p-1">
        <div id="categories" class="col-3">
            <vc:categories></vc:categories>
        </div>
        <div class="col-9">
            <div>
                @RenderBody()
            </div>
        </div>
    </div>
</body>
</html>